[[session]]
name = "Downloads ðŸ“¥"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "dotfiles"
path = "~/gitprojects/dotfiles"
startup_command = "nvim"
preview_command = "bat --color=always ~/gitprojects/dotfiles/tmux/.config/tmux/tmux.conf"

[[session]]
name = "Arbol"
path = "~/gitprojects/arbol/"
startup_command = "ls -latr"

[[session]]
name = "Lilypad ETL"
path = "~/gitprojects/arbol/lilypad/data_etl"
startup_command = "nvim"
